version: "3.4"
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infrastructure/database:/docker-entrypoint-initdb.d